spring.application.name=api-gateway
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.web-application-type=reactive
spring.cloud.compatibility-verifier.enabled=false
server.port=8181

# Connect to Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Disable auto-discovery routing (routes defined in GatewayConfig.java)
spring.cloud.gateway.discovery.locator.enabled=false

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics,gateway
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
